### ISSUE TITLE
build_all.sh error

### ISSUE THREAD

**Issue by LOVEChen** [Gernby/raspberry-pilot#1]
boardd.cc:21:10: fatal error: 'cereal/gen/cpp/log.capnp.h' file not found

**Comment by Gernby** [comment]
Thanks for the report, but could you provide more details?  What step are you at in the script when that occurred?

**Comment by Gernby** [comment]
If that was during the build_all step, would you try doing this instead?
cd ~/raspilot && pipenv run bash build_all.sh

**Comment by LOVEChen** [comment]
thanks Gernby , problem resolved

**Comment by LOVEChen** [comment]
i'll do this progress more than 10 times  always get that error

**Comment by LOVEChen** [comment]
and follow the process 

> ubuntu@ubuntu:~/raspilot$ pipenv run bash build_all.sh
Removing cereal/gen/
Removing selfdrive/can/obj/
rm -f boardd libcan_list_to_can_capnp.a boardd_api_impl.so boardd.o can_list_to_can_capnp.o ../common/swaglog.o ../common/params.o ../common/util.o ../../phonelibs/json/src/json.o ../../cereal/gen/c/log.capnp.o ../../cereal/gen/c/car.capnp.o boardd.d can_list_to_can_capnp.d ../common/swaglog.d ../common/params.d ../common/util.d ../../phonelibs/json/src/json.d ../../cereal/gen/c/log.capnp.d ../../cereal/gen/c/car.capnp.d
[ CXX ] boardd.o
clang++ -std=c++11 -g -fPIC -I../ -I../../ -O2 -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -Werror=int-conversion -Werror=return-type -Werror=format-extra-args -mcpu=cortex-a57 -I/usr/include/libusb-1.0 -MMD \
           -I../../phonelibs/capnp-c/include \
           -I../../phonelibs/capnp-cpp/include \
           -I../../phonelibs/zmq/aarch64/include \
           -I../ \
           -I../../ \
           -c -o 'boardd.o' 'boardd.cc'
boardd.cc:21:10: fatal error: 'cereal/gen/cpp/log.capnp.h' file not found
#include "cereal/gen/cpp/log.capnp.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Makefile:73: recipe for target 'boardd.o' failed
make: *** [boardd.o] Error 1
rm -rf libdbc.so*
rm -f dbc_out/*.cc
rm -f dbcs.txt
rm -f dbcs.csv
rm -rf obj/*
mkdir -p obj
cd ../../cereal && make
make[1]: Entering directory '/home/ubuntu/raspilot/cereal'
[ CAPNPC C++ ] gen/cpp/car.capnp.c++

**Comment by Rming** [comment]
`cd ~/raspilot/cereal && make` 
maybe help

**Comment by EasternPA** [comment]
My PR #5 fixes the illegal specifier error. The Pipfile has two components with their required level specified illegally. I added "==" before the required version and was able to clear that error.

**Comment by Gernby** [comment]
Thanks guys!  Please do a pull to get the fix
